### ISSUE TITLE
Bug on line 84

### ISSUE THREAD

**Issue by ckyleda** [TetsuyaOdaka/texture-synthesis-portilla-simoncelli#1]
Hello,

I think there is a minor bug which prevents the code as given from executing. 

Line 84 in steerable_pyramid.py is:

```self.ALPHAK = 2.**(self.K-1) * math.factorial(self.K-1)/np.sqrt(self.K * float(math.factorial(2.*(self.K-1))))```

However, math.factorial cannot take floating point numbers. This should be ```...float(math.factorial(2*(self.K-1))))```.

**Comment by TetsuyaOdaka** [comment]
Thanks.
I'll check it. Please give me some time.

**Comment by TetsuyaOdaka** [comment]
Fixed #1.
